# -*- coding: UTF-8 -*-

# 下载块事件
EVT_BLOCK_FINISH = '|BLO|FINISH|'
EVT_BLOCK_RETRY = '|BLO|RETRY|'

# 下载缓存事件
EVT_BUFFER_COUNT = '|BUFF|COUNT|'
EVT_BUFFER_RELEASE = '|BUFF|RELEASE|'

# 下载任务事件
EVT_TASK_ERROR = '|TASK|ERROR|'
EVT_TASK_PAUSING = '|TASK|PAUSING|'
EVT_TASK_PAUSED = '|TASK|PAUSED|'
EVT_TASK_SLICE = '|TASK|SLICE|'
EVT_TASK_FINISH = '|TASK|FINISH|'
EVT_TASK_SHUTDOWN = '|TASK|CLOSE|'

# 下载块客户端操作事件
EVT_CLIENT_SWITCH = '|CLI|SWITCH|'
EVT_CLIENT_WAIT = '|CLI|WAIT|'
EVT_CLIENT_RECV_EMPTY = '|CLI|EMPTY|'

# 下载源状态事件
EVT_URL_STATUS = '|URL|STATUS|'
EVT_URL_TIMEOUT = '|URL|TIMEOUT|'
EVT_URL_UNAVAILABLE = '|URL|CRASH|'
EVT_URL_UNKNOWN = '|URL|UNKNOWN|'
EVT_URL_GAIERROR = '|URL|GAIERROR|'
EVT_URL_NORMAL = '|URL|NORMAL|'

# 下载池管理器

# 下载池管理器针对下载任务添加的事件
EVT_TASK_OPENING = '|MGR|TASK|OPENING|'
EVT_TASK_START = '|MGR|TASK|START|'
EVT_TASK_CLOSED = '|MGR|TASK|CLOSED|'

# 下载池管理器的操作
EVT_MANAGER_START = '|MGR|START|'
EVT_MANAGER_PAUSED = '|MGR|STOP|'
EVT_MANAGER_SUSPEND = '|MGR|IDLE|'
EVT_MANAGER_SHUTDOWN = '|MGR|SHUTDOWN|'
EVT_MANAGER_ERROR = '|MGR|ERR|'

